REM COMMENT "Generated by cuetube 0.1.0 - Fri Sep 01 2017 17:01:02 GMT+0200 (Paris, Madrid (heure d’été))"
TITLE "3 HOURS of the Best Traditional Japanese Music - Relaxing Music for Stress Relief and Healing"
REM SRC "https://www.youtube.com/watch?v=pPFabRaQI-0"
PERFORMER "RELAX YOUR MIND"
FILE "https://www.youtube.com/watch?v=pPFabRaQI-0" MP3
  TRACK 01 MP3
    TITLE "3 HOURS of the Best Traditional Japanese Music. This soothing Japanese Music Playlist arrangement features of the best relaxing instrumentals of Japan. It is the perfect background music for stress relief and healing meditation sound therapy."
    INDEX 01 00:00:00
