PERFORMER "Scary Pockets"
TITLE "Stayin' Alive | ‪@beegees‬ | funk cover ft. ‪@LizzyMcAlpine"
REM SRC "https://www.youtube.com/watch?v=piTvLuHWLyg"
REM DATE "2022"
REM COMMENT "Generated by cuetube *.*.* - Wed Jan 07 2026 08:57:03 GMT+0100 (heure normale d’Europe centrale)"
FILE "https://www.youtube.com/watch?v=piTvLuHWLyg" MP3
  TRACK 01 MP3
  PERFORMER "Scary Pockets"
    TITLE "Stayin' Alive"
    INDEX 01 00:00:00
