TITLE "null"
REM SRC "https://www.youtube.com/watch?v=36JtMdp70h0&list=PL-f6lhHTNtYnofxTCiNh9Xsq9yHLG_VZ7"
REM COMMENT "Generated by cuetube *.*.* - Wed Jan 07 2026 08:57:03 GMT+0100 (heure normale d’Europe centrale)"
FILE "https://www.youtube.com/watch?v=36JtMdp70h0" MP3
  TRACK 01 MP3
    INDEX 01 00:00:00
