PERFORMER "Scary Pockets"
TITLE "null"
REM SRC "https://www.youtube.com/watch?v=FJ-seanImMw"
REM COMMENT "Generated by cuetube *.*.* - Wed Jan 07 2026 08:57:03 GMT+0100 (heure normale d’Europe centrale)"
FILE "https://www.youtube.com/watch?v=FJ-seanImMw" MP3
  TRACK 01 MP3
  PERFORMER "Scary Pockets"
    TITLE "Dancing Queen"
    INDEX 01 00:00:00
