PERFORMER "Mathieu Lavigne"
TITLE "Variété française"
REM SRC "https://www.youtube.com/playlist?list=PL04Bn5BSDltAfkwvn67CpaUQJmNJtugoJ"
REM COMMENT "Generated by cuetube *.*.* - Fri Mar 30 2018 10:09:23 GMT+0200 (Paris, Madrid (heure d’été))"
FILE "https://www.youtube.com/watch?v=ul33IBtf-vc" MP3
  TRACK 01 AUDIO
    TITLE "Les Innocents - L'autre Finistère (Clip officiel)"
    INDEX 01 00:00:00
